version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - [%(levelname)s] (%(name)s) %(message)s [%(filename)s:%(lineno)d]'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/general.log  # Default, will be overwritten dynamically
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  app:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, file_handler]
